# Generated by Django 5.0.2 on 2024-02-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_approval_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
