# Generated by Django 5.0.2 on 2024-02-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_approval_system_app', '0002_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
